version: "3"
services:
  drone:
    image: drone/drone:2
    links:
      - drone-db
    depends_on:
      - drone-db
    environment:
      - TZ=Asia/Shanghai
      - DRONE_AGENTS_ENABLED=true 
      - DRONE_GOGS_SERVER=${DRONE_GOGS_SERVER}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://drone:${POSTGRES_PASSWORD}@drone-db:5432/drone?sslmode=disable
  drone-runner:
    image: drone/drone-runner-docker:1
    links:
      - drone
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_HOST=${DRONE_SERVER_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_NAME=my-first-runner
  drone-db:
    image: postgres:alpine
    volumes:
      - drone-db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=drone
      - POSTGRES_DB=drone
volumes:
  drone-db: